controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    position_controllers:
      type: position_controllers/JointGroupPositionController

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController


position_controllers:
  ros__parameters:
    joints:
      - base
      - shoulder
      - elbow
      - wrist1
      - wrist2
      - wrist3


joint_trajectory_controller:
  ros__parameters:
    joints:
      - base
      - shoulder
      - elbow
      - wrist1
      - wrist2
      - wrist3

    command_interfaces:
      - position

    state_interfaces:
      - position

    action_monitor_rate: 20.0

    allow_partial_joints_goal: false
    open_loop_control: true
    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.0